### PR TITLE
Added required files for Visual Studio

### PR DESCRIPTION
**Pull request by irrld**
This PR adds required files for opening the project in Visual Studio as well as some README changes.

Tested with VS2017 and VS2022 on Windows 11

### CODE REVIEW

**Comment by noyanc** [comment]
@irrld Do we have to download the repo as zip? Can not we clone it via git?

**Comment by irrld** [comment]
Yes we can clone via git, downloading is simpler for adding it to existing projects, it's totally optional.

**Comment by noyanc** [comment]
Can you please edit the Readme for cloning. We shouldn't suggest downloading, but cloning.

**Comment by irrld** [comment]
Done

**Comment by noyanc** [comment]
@irrld And how Visual Studio users get glistengine and libraries under zbin? Do they have to clone all 3 repos, then open the glistapp with Visual Studio? If so, we should add Visual Studio explications into the Readme of GlistEngine, not GlistApp.

**Comment by irrld** [comment]
Same installation progress of GlistEngine applies to Visual Studio (Same folder structure etc.), we can still add these to GlistEngine instead of GlistApp.

**Pull request closed without merging**
